[package]
name = "muw-community-thesis-templates"
version = "0.0.0"
entrypoint = "thesis/main.typ"
authors = ["Felix D"]
repository = "https://github.com/felixbd/muw-thesis"
license = "MIT"
keywords = ["muw", "MedUni", "Wien", "Medizinische Universität Wien", "Medical University of Vienna"]
categories = ["thesis"]
description = "community thesis templates for 'Medical University of Vienna'"
exclude = ["Makefile", "thesis-out.pdf", "thumbnail-page-01.png"]

[template]
path = "thesis/"
entrypoint = "main.typ"
thumbnail = "thumbnail-page-01.png"
